README.md, apps/dashboard/src/main/java/com/akto/action/HarAction.java, apps/dashboard/src/main/java/com/akto/utils/DashboardMode.java
=> Steps to start testing module

apps/testing/src/main/java/com/akto/rules/FuzzingTest.java, apps/testing/src/main/java/com/akto/testing/TestExecutor.java
1. Added check for NULL hosts before running Nuclei tests
=> added a check for null hosts for nuclei tests

.github/workflows/prod.yml, .github/workflows/staging.yml, README.md
Seperated the existing Github workflow into two files:
- staging.yml - push docker images tagged as akto1, akto2, akto3
- prod.yml - push docker image tagged as local
=> Separate Production/Staging Github workflow

.github/workflows/prod.yml, .github/workflows/staging.yml
Changes:
- staging.yaml
- Added branch names to end of staging docker image tags
- prod.yaml
- Removed prod/staging environment input and conditional execution
- Removed tag input
- Added release version input
- Added docker image tagging  - local, version_local
- Added git tags for release 
- Added github releases 
- Added slack notifications
=> Add semantic versioning

.devcontainer/devcontainer.json, .devcontainer/docker-compose.devcontainer.yml, README.md
Changed application port to 9090 in devcontainer and manual install to prevent conflicts with Burp Suite
=> changed port configuration

apps/testing/src/main/java/com/akto/rules/PageSizeDosTest.java
Add more case sensitive keys for page size DoS test
=> Issue 229 -  Add more case sensitive keys for page size DoS test

apps/dashboard/web/src/apps/login/App.vue
fixes #211 
The "Login" button on the main page doesn't have the correct color.
fixed by adding the background color:
background: linear-gradient(100deg,var(--backgroundColor1) -17.13%,var(--themeColor) 99.86%)
=> Fixed login button color

.github/workflows/beamer.yml
Used cURL to make POST request to API Endpoint.
=> Automate product releases on beamer #236

apps/dashboard/web/src/apps/dashboard/shared/components/SampleSingleSide.vue
Added focus() and [selectionRange()](https://masteringjs.io/tutorials/vue/copy-to-clipboard) as suggested.
Fixes #153
=> added selection range

libs/utils/src/main/java/com/akto/notifications/slack/TestSummaryGenerator.java
Allow only open issues in slack alert
=> Allow only open issues in slack alert

.github/workflows/beamer.yml
=> fixed beamer workflow

apps/testing/src/main/java/com/akto/test_editor/execution/Executor.java
… auth in replace auth header executor
=> remove custom auth in replace auth header test and remove all custom auth instead of removing only one

apps/api-runtime/src/main/java/com/akto/runtime/APICatalogSync.java, apps/dashboard/src/main/java/com/akto/utils/Utils.java
Reverts akto-api-security/akto#512
=> Revert "allow merging to happen after har upload"

pii-types/fintech.json
Fix trailing comma issue in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json#L10-L11) file
=> fix(fintech.json): trailing comma

apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java, pii-types/fintech.json
Fixes : https://github.com/akto-api-security/akto/issues/99
=> Add sensitive data Cookie types

apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java, pii-types/fintech.json
=> Adds sensitive data types for Database URL patterns

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiCollections.jsx
Refer to Issue no. #155.
Now, it refreshes every 10 seconds. Please review the changes and update me if I need to make any changes. Thanks :)
=> Added auto-refresh functionality

apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/layouts/header/Headers.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/shared/SampleDataComponent.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/shared/customDiffEditor.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/dashboard.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/TestRoleSettings.jsx, apps/dashboard/web/polaris_web/web/src/util/func.js
fixes beamer UI and query params in sample data UI.
=> fix beamer UI

.github/workflows/akto-inventory.yaml, .github/workflows/beamer.yml, .github/workflows/beamerAndDiscord.yml, .github/workflows/codeql.yml, .github/workflows/csvUpdate.yml, .github/workflows/discord-release-msg.yml, .github/workflows/prod.yml, .github/workflows/releaseOnlyUI.yml, .github/workflows/semgrep.yml, .github/workflows/staging.yml, .github/workflows/testsigma.yml
✔ Bolted discord-release-msg.yml with bolt
✔ Bolted releaseOnlyUI.yml with bolt
✔ Bolted staging.yml with bolt
✔ Bolted akto-inventory.yaml with bolt
✔ Bolted beamer.yml with bolt
✔ Bolted testsigma.yml with bolt
✔ Bolted codeql.yml with bolt
✔ Bolted csvUpdate.yml with bolt
✔ Bolted beamerAndDiscord.yml with bolt
✔ Bolted prod.yml with bolt
✔ Bolted semgrep.yml with bolt
=> adding bolt to all the workflows

libs/dao/src/main/java/com/akto/util/enums/GlobalEnums.java
=> Added new Enum for Improper Inventory Management

libs/dao/src/main/java/com/akto/DaoInit.java, libs/dao/src/main/java/com/akto/dao/AccountsDao.java, libs/dao/src/main/java/com/akto/dao/SingleTypeInfoDao.java, libs/dao/src/main/java/com/akto/dao/UsersDao.java
Added 3 new indices in the following documents:
1. common.users
2. common.accounts
3. 1000000.single_type_info
=> add indexing in users, accounts and singletypeinfo docs

apps/dashboard/src/main/java/com/akto/listener/RuntimeListener.java
Reverts akto-api-security/akto#999
=> Revert "remove account id check"

libs/dao/src/main/java/com/akto/dto/test_editor/Info.java
Added remediation field for Templates
=> Added remediation field

libs/dao/src/main/java/com/akto/dto/AccountSettings.java
Reverts akto-api-security/akto#1206
=> Revert "update ony new stis if flag enabled"

apps/dashboard/src/main/java/com/akto/action/InviteUserAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiDetails.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/TestEditor.jsx
ui fix in inventory
Invite user fix for no email sent case
removing beta from test editor
=> invite user fix

libs/dao/src/main/java/com/akto/util/enums/GlobalEnums.java
Added 4 new categories:
- SQL Injection
- NoSQL Injection
- XML Injection
- Input Validation
=> add new TestCategory

libs/dao/src/main/java/com/akto/util/enums/GlobalEnums.java
Input Validation category added
=> added new category

apps/database-abstractor/src/main/java/com/akto/action/DbAction.java
Reverts akto-api-security/akto#1467
=> Revert "skip bulk updates for account"

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/CreateNewCollectionModal.jsx
…sabled if the name input is empty
=> Removing the error from new collection modal

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiCollections.jsx
Made hostname tab as default and fixed deactivate collection tab.
=> Hostname tab as default

apps/dashboard/src/main/java/com/akto/action/ApiCollectionsAction.java, apps/dashboard/src/main/java/com/akto/action/DashboardAction.java, apps/dashboard/src/main/java/com/akto/action/observe/InventoryAction.java, apps/dashboard/src/main/java/com/akto/action/testing_issues/IssuesAction.java, apps/dashboard/src/main/resources/struts.xml, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/dashboard/HomeDashboard.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/dashboard/api.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/issues/IssuesPage/SummaryInfo.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/issues/api.js, libs/dao/src/main/java/com/akto/dao/SingleTypeInfoDao.java
Reverts akto-api-security/akto#1663
=> Revert "Feature/api security posture graph fix"

apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/layouts/header/Headers.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/layouts/leftnav/LeftNav.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/dashboard.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/TestEditor.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/TestEditor.jsx, apps/dashboard/web/polaris_web/web/src/apps/signup/styles.css
Additional added css removed for polaris 12
@Ark2307 Have a look.
=> additional added css removed for polaris 12

apps/mini-testing/src/main/java/com/akto/testing/TestExecutor.java
Reverts akto-api-security/akto#1836
=> Revert "parallelise tests based on no of tests if api count is low"

.github/workflows/prod.yml, .github/workflows/staging.yml, libs/protobuf/pom.xml, scripts/install-protoc-mac.sh
also added install script for installing buf and protoc for mac in scripts folder
=> using 29.2 protoc version

README.md
This reverts commit 5fdcd3e373911d8e85bd96775735e8465f63329c.
=> Revert "dummy commit"

apps/testing/src/main/java/com/akto/testing/workflow_node_executor/YamlNodeExecutor.java
Reverts akto-api-security/akto#2006
=> Revert "abort current block if found vuln"

libs/utils/src/main/java/com/akto/usage/UsageMetricCalculator.java
updating billing mechanism from monthly to total apis
=> update billing mechanism

apps/dashboard/src/main/java/com/akto/action/testing_issues/IssuesAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTest.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTestSuites.jsx
=> intrusive and non-intrusive added

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTestSuites.jsx
@Ark2307 @notlazykid 
just found a bug in checkDisableTestSuite
earlier it is not making test Suite disable
=> minor bug fixed in checkDisableTestSuite

apps/dashboard/src/main/java/com/akto/action/test_editor/SaveTestEditorAction.java, apps/dashboard/src/main/resources/struts.xml, apps/dashboard/src/test/java/com/akto/action/testing/TestSaveTestEditorAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/api.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/TestsFlyLayout.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/TestsTablePage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/transform.js
=> load time reduced made and api to only fetch test content

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/TestsTablePage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/transform.js
=> compliance added

apps/dashboard/src/main/java/com/akto/action/test_editor/SaveTestEditorAction.java, apps/dashboard/src/main/resources/struts.xml, apps/dashboard/src/test/java/com/akto/action/testing/TestSaveTestEditorAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/layouts/leftnav/LeftNav.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/shared/ShowListInBadge.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/TestEditor.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/api.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/TestsFlyLayout.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/TestsTablePage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/tests_table/YamlComponent.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/test_editor/transform.js, apps/dashboard/web/polaris_web/web/src/apps/main/App.js, apps/dashboard/web/polaris_web/web/src/apps/main/onboardingData.js
Reverts akto-api-security/akto#2123
=> Revert "Revert "Test library Screen""

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRolesPage/TestRolesPage.jsx
=> test role table changed

apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/layouts/DateRangePicker.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTest.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTestConfiguration.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRunsPage/TestRunsPage.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/transform.js, apps/dashboard/web/polaris_web/web/src/util/func.js, apps/dashboard/web/polaris_web/web/src/util/values.js
Quick fixes:
1. Change the run test button label
2. Schedule status fix
3. Run type bug fix - Select date disappears if switched to diff run type
4. All dates (Past & Future) - New timeline in time filter selector in order to show tests which have been scheduled for future dates.
=> Schedule test

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRolesPage/TestRolesPage.jsx
=> test role name font weight fix

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/issues/IssuesPage/IssuesPage.jsx
=> export as csv added for issue table

apps/dashboard/src/main/java/com/akto/action/testing/TestRolesAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRolesPage/TestRolesPage.jsx, libs/dao/src/main/java/com/akto/dto/testing/TestRoles.java
=> No of auth, Type of auth , no of test added to test role table

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/testSuite/FlyLayoutSuite.jsx
=> flyLayoutSuite footer fixed

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/agent_team/AgentTeam.tsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/agent_team/agents/FindVulnerabilities.tsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/agent_team/components/ActivityTable.tsx
=> agent status sync finished

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/AllSensitiveData/AllSensitiveData.jsx
Rename data state keys in AllSensitiveData component for clarity; updated related logic.
=> New detect tab in sensitive data page

apps/dashboard/src/main/java/com/akto/action/testing/StartTestAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTest.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTestSuiteRow.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/RunTestSuites.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/Utils.js, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/run_test_suites.css, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/transform.js, apps/dashboard/web/polaris_web/web/src/util/func.js, apps/testing/src/main/java/com/akto/testing/TestExecutor.java, libs/dao/src/main/java/com/akto/dto/testing/TestingRunConfig.java
1. checkbox replaced by radiobutton for suite
2. generated suite are send to server by list and custom by id
3. modifyTestingRunConfig updated
=> feature/test_suite_rerun_test: testSuite is now radioButton, generated  test suite send by list

apps/dashboard/src/main/java/com/akto/action/ApiCollectionsAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/SensitiveDataExposure/SensitiveDataExposure.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiCollections.jsx
1. create api group bug fixed
2. api group removed allowed now
=> create api group bug fixed and api group removed allowed

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiEndpoints.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/transform.js, apps/dashboard/web/polaris_web/web/src/util/func.js
=> issue column added in apiEndpoints table

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/settings/Settings.jsx
and add Esc key listener for closing settings
=> Implement back navigation on settings close

apps/dashboard/src/main/java/com/akto/action/testing/TestRolesAction.java, apps/dashboard/src/main/resources/struts.xml, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/AuthComponent.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/DeleteModal.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/DescriptionCard.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/SavedParamComponent.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/ScopeRoleDropdown.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/TestRoleConstants.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRoleSettings/TestRoleSettings.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/TestRolesPage/TestRolesPage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/testing/api.js, libs/dao/src/main/java/com/akto/dto/testing/TestRoles.java
--separated components  test role settings page
--added feature based dropdown for scope role selection
--filter test roles according to user role for running test
--added logic for backward compatibility.
=> TestRole Suggestions based on Rbac

apps/threat-detection/src/main/java/com/akto/threat/detection/Main.java, apps/threat-detection/src/main/java/com/akto/threat/detection/tasks/MaliciousTrafficDetectorTask.java, libs/utils/src/main/java/com/akto/log/LoggerMaker.java
- GetRedisclient doesn't actually check for redis connection.
- Added a check to test
=> Fix threat client when cache not available

apps/dashboard/src/main/java/com/akto/action/gpt/handlers/QueryHandlerFactory.java, apps/dashboard/src/main/java/com/akto/action/gpt/handlers/gpt_prompts/AnalyzeRequestResponseHeaders.java, apps/dashboard/src/main/java/com/akto/action/gpt/handlers/gpt_prompts/PromptHandler.java, apps/dashboard/src/main/java/com/akto/action/gpt/result_fetchers/SelfHostedLlmResultFetcherStrategy.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiDetails.jsx, libs/dao/src/main/java/com/akto/util/Constants.java
- rewrite prompt from lambda to akto repo
- added support to use self hosted llm
- uncommented askAI call code in ApiDetails.jsx file
=> redirected req and resp headers gpt request to self hosted llm

apps/database-abstractor/src/main/java/com/akto/action/DbAction.java, apps/mini-runtime/src/main/java/com/akto/hybrid_parsers/HttpCallParser.java, apps/mini-runtime/src/main/java/com/akto/hybrid_runtime/Main.java, libs/dao/src/main/java/com/akto/DaoInit.java, libs/dao/src/main/java/com/akto/dto/ApiCollection.java, libs/dao/src/main/java/com/akto/dto/HttpResponseParams.java, libs/dao/src/main/java/com/akto/dto/traffic/CollectionTags.java, libs/dao/src/test/java/com/akto/dto/traffic/CollectionTagsTest.java, libs/utils/src/main/java/com/akto/data_actor/ClientActor.java, libs/utils/src/main/java/com/akto/data_actor/DataActor.java, libs/utils/src/main/java/com/akto/data_actor/DbActor.java, libs/utils/src/main/java/com/akto/data_actor/DbLayer.java, libs/utils/src/main/java/com/akto/log/LoggerMaker.java, libs/utils/src/main/java/com/akto/runtime/parser/SampleParser.java
Send tags with createCollection from mini-runtime.
K8 pod labels -> Mirroring -> Runtime -> Cyborg -> DB.
Adds the K8 tags as headers with prefix.
`x-akto-k8s-tagname: tagvalue`
=> Add tags in create collection

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiCollections.jsx
=> show key name of tags

.github/workflows/data-ingestion.yml
=> Fix data ingestion action

libs/utils/src/main/java/com/akto/test_editor/Utils.java, libs/utils/src/main/java/com/akto/test_editor/execution/Operations.java, libs/utils/src/main/java/com/akto/test_editor/filter/FilterAction.java
add feature
ref:
https://github.com/akto-api-security/akto/pull/2536/files
https://github.com/akto-api-security/akto/pull/2532/files
https://github.com/akto-api-security/akto/pull/2529/files
=> add nested support

libs/dao/src/main/java/com/akto/dto/traffic/CollectionTags.java, libs/utils/src/main/java/com/akto/data_actor/DbLayer.java
This will add the tags of all the service where the request was incoming.
=> Append the tags

libs/dao/src/main/java/com/akto/dto/traffic/CollectionTags.java, libs/utils/src/main/java/com/akto/data_actor/DbLayer.java
Reverts akto-api-security/akto#2731
=> Revert "Append the tags"

libs/utils/src/main/java/com/akto/data_actor/DbLayer.java
Deduplicate tags before adding to DB.
=> use hashSet to deduplicate.

apps/dashboard/src/main/java/com/akto/action/threat_detection/DashboardMaliciousEvent.java, apps/dashboard/src/main/java/com/akto/action/threat_detection/SuspectSampleDataAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/threat_detection/ThreatDetectionPage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/threat_detection/api.js, apps/threat-detection-backend/src/main/java/com/akto/threat/backend/service/MaliciousEventService.java, protobuf/threat_detection/service/dashboard_service/v1/service.proto
Reverts akto-api-security/akto#2825
=> Revert "Feature/download malicious requests"

apps/dashboard/src/main/java/com/akto/action/threat_detection/DashboardMaliciousEvent.java, apps/dashboard/src/main/java/com/akto/action/threat_detection/SuspectSampleDataAction.java, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/threat_detection/ThreatDetectionPage.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/threat_detection/api.js, apps/threat-detection-backend/src/main/java/com/akto/threat/backend/service/MaliciousEventService.java, protobuf/threat_detection/service/dashboard_service/v1/service.proto
Reverts akto-api-security/akto#2831
=> Revert "Revert "Feature/download malicious requests""

apps/dashboard/src/main/java/com/akto/action/ApiCollectionsAction.java
Reverts akto-api-security/akto#2861
=> Revert "Fix urls count"

apps/dashboard/src/main/java/com/akto/listener/InitializerListener.java
Allow API groups crons to run for automated discover of new endpoints.
=> Allow API Crons Jobs to run

apps/dashboard/src/main/java/com/akto/action/InviteUserAction.java
Removed initialization of commonOrganisationsMap.
=> Remove static initialization of commonOrganisationsMap

.github/workflows/prod.yml, apps/mini-runtime/src/main/java/com/akto/hybrid_parsers/HttpCallParser.java, apps/mini-runtime/src/main/java/com/akto/hybrid_runtime/APICatalogSync.java, apps/mini-runtime/src/main/java/com/akto/hybrid_runtime/Main.java, apps/mini-runtime/src/main/java/com/akto/hybrid_runtime/MergeLogicLocal.java
Separated out Postgres DB merging from Traffic Consumption.
Refactored the main function into smaller functions.
@notshivansh 
- DB_MERGING_MODE: true , only postgres merging will run
- If false, existing functionality will run. Regression testing to check everything works has been done.
@ayushaga14 FYI Protobuff push changes I did not test, they are very minor. Should work.
Test cases
=> Refactor main class, use db merging mode

libs/dao/src/main/java/com/akto/dao/SingleTypeInfoDao.java, libs/dao/src/main/java/com/akto/dto/ApiCollectionUsers.java
Reverts akto-api-security/akto#3085
=> Revert "remove sti query"

apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/quick_start/AIAgentsGateway.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/quick_start/McpGateway.jsx, apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/quick_start/transform.js
1. Added MCP proxy and gateway option
2. Added Ai agents proxy and gateway
=> added gateway in mcp and ai agents
